# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxCocoaExamples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxAlamofire', '~> 4.0.0-rc.0'
  pod 'SwiftyJSON'
  pod 'RxSwift', '4.0.0-rc.0'
  pod 'RxCocoa', '4.0.0-rc.0'
  pod 'FirebaseDatabase', '~> 4.1'
  # Pods for RxCocoaExamples

end
